import React, { useState } from 'react';
import { ResearchResult, Language, CitationStyle } from '../types';
import { generateLiteratureReview } from '../services/geminiService';
import { PenTool, FileCode, FileType, Loader2, Sparkles, SlidersHorizontal } from './Icons';
import ReactMarkdown from 'react-markdown';

interface LiteratureReviewSectionProps {
  result: ResearchResult;
  language: Language;
  existingReview: string | null;
  onReviewGenerated: (review: string) => void;
}

export const LiteratureReviewSection: React.FC<LiteratureReviewSectionProps> = ({ 
  result, 
  language, 
  existingReview,
  onReviewGenerated 
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [citationStyle, setCitationStyle] = useState<CitationStyle>('apa');

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const review = await generateLiteratureReview(result, language, citationStyle);
      onReviewGenerated(review);
    } catch (err: any) {
      setError(err.message || "Failed to generate literature review.");
    } finally {
      setLoading(false);
    }
  };

  const handleExportMarkdown = () => {
    if (!existingReview) return;
    const blob = new Blob([existingReview], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LiteratureReview-${result.topic.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const escapeLatexText = (text: string) => {
     // First handle structure mappings (heuristic)
     // Then escape special characters in the content
     return text
       .replace(/\\/g, '\\textbackslash{}') // Backslash first
       .replace(/&/g, '\\&')
       .replace(/%/g, '\\%')
       .replace(/\$/g, '\\$')
       .replace(/#/g, '\\#')
       .replace(/_/g, '\\_')
       .replace(/{/g, '\\{')
       .replace(/}/g, '\\}')
       .replace(/\^/g, '\\textasciicircum{}')
       .replace(/~/g, '\\textasciitilde{}');
  };

  const convertMarkdownToLatex = (md: string) => {
    // Simple converter that handles headers and basic formatting while ensuring safety
    const lines = md.split('\n');
    let inList = false;
    
    const latexLines = lines.map(line => {
      const trimmed = line.trim();
      
      // Headers
      if (line.startsWith('### ')) return `\\subsubsection*{${escapeLatexText(line.replace('### ', ''))}}`;
      if (line.startsWith('## ')) return `\\subsection*{${escapeLatexText(line.replace('## ', ''))}}`;
      if (line.startsWith('# ')) return `\\section*{${escapeLatexText(line.replace('# ', ''))}}`;
      
      // Lists
      if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
         const item = `  \\item ${escapeLatexText(trimmed.substring(2))}`;
         if (!inList) {
           inList = true;
           return `\\begin{itemize}\n${item}`;
         }
         return item;
      }
      
      // End List if needed
      if (inList && trimmed === '') {
        inList = false;
        return '\\end{itemize}\n';
      }

      if (trimmed === '') return '';

      // Bold/Italic regex replacement (careful with already escaped chars)
      // We escape text first, then apply bold/italic wrappers
      let content = escapeLatexText(line);
      // Restore some markdown intent that got escaped? 
      // Actually, it's safer to escape everything. But let's try to support bold/italic.
      // The escapeLatexText escapes * and _. So strict markdown to latex is hard without a parser.
      // Given the user's error was specifically about '&', strictly escaping everything is the safest 
      // way to ensure it compiles, even if we lose bolding.
      
      // However, we can try a smart replace for bold **text** -> \textbf{text} 
      // by assuming ** didn't contain special chars that needed escaping or handling strictly.
      // For now, prioritized safety against "Misplaced alignment tab character &".
      
      return content + '\n';
    });

    if (inList) {
      latexLines.push('\\end{itemize}');
    }

    return latexLines.join('\n');
  };

  const handleExportLatex = () => {
    if (!existingReview) return;
    
    const bodyContent = convertMarkdownToLatex(existingReview);

    const latexContent = `\\documentclass{article}
\\usepackage[utf8]{inputenc}
\\usepackage{geometry}
\\geometry{a4paper, margin=1in}
\\usepackage{hyperref}

\\title{Literature Review: ${escapeLatexText(result.topic)}}
\\date{\\today}

\\begin{document}

\\maketitle

% Generated by DeepResearch AI

${bodyContent}

\\end{document}`;

    const blob = new Blob([latexContent], { type: 'application/x-latex' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LiteratureReview-${result.topic.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.tex`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-8 break-inside-avoid">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <PenTool className="text-blue-600" />
            Literature Review
          </h2>
          <p className="text-slate-500 text-sm mt-1">
            Generate an academic review based on the selected articles.
          </p>
        </div>
      </div>

      {!existingReview && !loading && (
        <div className="flex flex-col items-center justify-center p-8 border-2 border-dashed border-slate-200 rounded-xl bg-slate-50">
          <Sparkles className="w-10 h-10 text-blue-400 mb-3 opacity-50" />
          <p className="text-slate-600 mb-4 text-center max-w-md">
            Synthesize the findings from the {result.articles.length} articles into a cohesive literature review.
          </p>
          
          <div className="flex flex-col gap-4 w-full max-w-xs">
             <div className="flex flex-col gap-2">
               <label className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-2">
                 <SlidersHorizontal size={12} /> Citation Style
               </label>
               <select 
                 value={citationStyle}
                 onChange={(e) => setCitationStyle(e.target.value as CitationStyle)}
                 className="w-full p-2.5 rounded-lg border border-slate-300 bg-white text-sm text-slate-700 focus:ring-2 focus:ring-blue-500 outline-none"
               >
                 <option value="apa">APA 7th (Author, Year)</option>
                 <option value="ieee">IEEE [1] (Numeric)</option>
                 <option value="mla">MLA (Author Page)</option>
                 <option value="harvard">Harvard (Author Year)</option>
               </select>
             </div>

             <button
              onClick={handleGenerate}
              className="w-full px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium flex items-center justify-center gap-2 transition-colors shadow-lg shadow-blue-900/20"
            >
              <PenTool size={18} />
              Generate Review
            </button>
          </div>
          
          {error && (
            <p className="mt-4 text-red-500 bg-red-50 px-4 py-2 rounded text-sm">{error}</p>
          )}
        </div>
      )}

      {loading && (
        <div className="flex flex-col items-center justify-center py-12">
          <Loader2 className="w-10 h-10 text-blue-600 animate-spin mb-4" />
          <p className="text-slate-600 font-medium">Synthesizing literature...</p>
          <p className="text-slate-400 text-sm">Applying {citationStyle.toUpperCase()} citation style</p>
        </div>
      )}

      {existingReview && (
        <div className="animate-fade-in">
          <div className="flex justify-end gap-2 mb-4 print:hidden">
            <button 
              onClick={handleExportMarkdown}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
            >
              <FileType size={16} /> Markdown
            </button>
            <button 
              onClick={handleExportLatex}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
            >
              <FileCode size={16} /> LaTeX
            </button>
          </div>

          <div className="prose prose-slate max-w-none p-6 bg-slate-50 rounded-xl border border-slate-100">
             <ReactMarkdown>{existingReview}</ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  );
};